const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const root=path.join(__dirname,'..'),source=fs.readFileSync(path.join(root,'app/src/main/assets/named-walk.js'),'utf8');
assert.equal(source,fs.readFileSync(path.join(root,'app/src/main/assets/named-walk.js'),'utf8'));
new vm.Script(source);
const box={};vm.createContext(box);vm.runInContext(source.slice(source.indexOf('function buildNamedWalkPlan('),source.indexOf('function showNamedWalkPlan(')),box);
const mapping={lf:1,rr:3,rf:5,lr:2,slide:6};
const rows=Object.values(mapping).map(channel=>({channel,name:'Joint '+channel,enabled:true,calibrated:true,a_name:channel===6?'Back':'Up',b_name:channel===6?'Forward':'Down',a_us:channel===1?1700:1200,b_us:channel===1?1100:1800,center_us:1500}));
const plan=box.buildNamedWalkPlan(rows,mapping);
assert.equal(plan.speed_us_s,800);assert.equal(plan.cycles,3);
assert.equal(box.buildNamedWalkPlan(rows,mapping,250,8).cycles,8);
for(const cycles of [0,11,1.5,NaN])assert.throws(()=>box.buildNamedWalkPlan(rows,mapping,400,cycles),/cycles/);
for(const speed of [0,1601,100.5,NaN])assert.throws(()=>box.buildNamedWalkPlan(rows,mapping,speed,3),/speed/);
assert.equal(box.buildNamedWalkPlan(rows,mapping,1000,3,50,true,20).paired_feet,true);
for(const settle of [-1,501,NaN])assert.throws(()=>box.buildNamedWalkPlan(rows,mapping,1000,3,50,true,settle),/Settling/);
assert.deepEqual(JSON.parse(JSON.stringify(plan.steps.map(s=>[s.channel,s.position]))),[[1,'Up'],[3,'Up'],[6,'Back'],[1,'Down'],[3,'Down'],[5,'Up'],[2,'Up'],[6,'Forward'],[5,'Down'],[2,'Down']]);
assert.equal(plan.steps[0].binding.a_us,1700,'Up can be the larger pulse');
const reordered=JSON.parse(JSON.stringify(plan));
reordered.steps=reordered.steps.map(s=>({binding:Object.fromEntries(Object.entries(s.binding).reverse()),position:s.position,channel:s.channel}));
assert.equal(box.sameNamedWalkPlan(reordered,plan),true,'MicroPython JSON key order does not change plan identity');
reordered.speed_us_s=100;assert.equal(box.sameNamedWalkPlan(reordered,plan),false,'changed speed must not be marked saved');
reordered.speed_us_s=800;reordered.cycles=2;assert.equal(box.sameNamedWalkPlan(reordered,plan),false,'changed cycles must not be marked saved');
reordered.cycles=3;reordered.steps[0].binding.a_us++;assert.equal(box.sameNamedWalkPlan(reordered,plan),false,'changed endpoints must not be marked saved');
assert.throws(()=>box.buildNamedWalkPlan(rows,{...mapping,rf:1}),/different outputs/);
rows[0].calibrated=false;assert.throws(()=>box.buildNamedWalkPlan(rows,mapping),/Calibrate/);
console.log('PASS: exact ten-step order, physical channel mapping, bound calibration and mirror parity.');
