const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const data=new Map(),status={textContent:''};
const box={localStorage:{getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v)},NW:{plan:{version:1,speed_us_s:1600,lift_percent:50,steps:[{channel:1,position:'Up',binding:{a_us:500}}]}},CHANNEL_SETUP:{loaded:true},$:()=>status};
vm.createContext(box);const source=fs.readFileSync(path.join(__dirname,'../app/src/main/assets/travel-estimate.js'),'utf8');vm.runInContext(source,box);
const sample={cycles:6,feet:1,pace:'run',direction:'forward',surface:'carpet'},request={distance_ft:3,pace:'run',direction:'forward',surface:'carpet'};
assert.equal(box.estimateTravel(request).calibrated,false,'no measurement means unknown, not a guessed camera distance');
box.saveTravelMeasurement(sample);let r=box.estimateTravel(request);
assert.equal(r.nominalCycles,18);assert.equal(r.nextSegmentCycles,18);assert.equal(r.actualPositionKnown,false);assert.equal(r.observedCycleRange,null);
assert.equal(box.estimateTravel({...request,distance_ft:10}).nextSegmentCycles,30);
assert.equal(box.estimateTravel({...request,distance_ft:0}).nominalCycles,0);
assert.equal(box.estimateTravel({...request,stop_short_ft:1}).nominalCycles,12);
for(const delta of [{pace:'slow'},{direction:'backward'},{surface:'tile'}])assert.equal(box.estimateTravel({...request,...delta}).calibrated,false);
box.NW.plan.cycles=3;assert.equal(box.estimateTravel(request).calibrated,true,'number requested does not change the per-cycle gait');
box.NW.plan.lift_percent=60;assert.equal(box.estimateTravel(request).calibrated,false,'changed lift invalidates old calibration');box.NW.plan.lift_percent=50;
box.saveTravelMeasurement({...sample,cycles:6,feet:1.2});r=box.estimateTravel(request);assert.deepEqual(Array.from(r.observedCycleRange),[15,18]);
box.saveTravelMeasurement({...sample,surface:'tile'});assert.equal(box.estimateTravel({...request,surface:''}).calibrated,false,'different floors cannot silently mix');
box.saveTravelMeasurement({...sample,feet:0});assert.equal(box.estimateTravel(request).calibrated,false,'feet cycling without travel is not a distance estimate');
box.undoTravelMeasurement();assert.equal(box.estimateTravel(request).calibrated,true);
for(const bad of [{distance_ft:NaN},{distance_ft:-1},{distance_ft:Infinity},{pace:'turbo'}])assert.throws(()=>box.estimateTravel({...request,...bad}));
box.NW.running=true;assert.throws(()=>box.saveTravelMeasurement(sample));box.NW.running=false;
data.set('owlbot_travel_calibration_v1','corrupt');assert.throws(()=>box.saveTravelMeasurement(sample));assert.equal(data.get('owlbot_travel_calibration_v1'),'corrupt','bad stored data must not be erased');
assert.doesNotMatch(source,/channelCommand\(|wsSend\(|runNamedForwardWalk\(/);
console.log('PASS: measured distance/cycle estimates, gait-speed-surface isolation, uncertainty, zero-travel rejection, undo and no motor commands.');
