const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=__dirname+'/../app/src/main/assets/',html=fs.readFileSync(root+'growbot-brain.html','utf8');
let clock=1800000000000,saves=0;
const box={Date:class extends Date{static now(){return clock}},MEM:{initiatives:[],answeredQuestions:[],shared:[],conversations:[],currentPerson:'aaron'},memSave:()=>saves++};
vm.createContext(box);vm.runInContext(fs.readFileSync(root+'question-continuity.js','utf8'),box);
vm.runInContext(html.slice(html.indexOf('function lastOpenSocialQuestion('),html.indexOf('function ago(')),box);
const ask='I found a yellow jug on the floor. Do you know what it actually is?';
box.rememberSpokenQuestion(ask);assert.equal(box.MEM.initiatives.length,1);
box.rememberSocialInitiative(ask,'wonder');assert.equal(box.MEM.initiatives.length,1,'social delivery and central voice hook do not double-count');
const context=box.captureSocialAnswer("It's not cleaning it's adhesive remover");
assert.match(context,/adhesive remover/);assert.equal(box.MEM.answeredQuestions.length,1);
assert.equal(box.MEM.answeredQuestions[0].subject,'yellow container');
assert(box.repeatedAnsweredQuestion('What is that yellow bucket?'),'paraphrased same-object identification is withheld');
assert(!box.repeatedAnsweredQuestion('Is the yellow jug cap closed?'),'new cap question stays possible');
assert(!box.repeatedAnsweredQuestion('What is the yellow jug used for?'),'purpose differs from identity');
assert(!box.repeatedAnsweredQuestion("What's inside the yellow jug?"),'hidden contents are a distinct question');
assert(!box.repeatedAnsweredQuestion('Where is the yellow jug?'));
assert(!box.repeatedAnsweredQuestion('What is that red bucket?'),'different object is not suppressed');
assert(!box.repeatedAnsweredQuestion('I see a blue bottle. Do you know what it actually is?'),'pronoun question must bind to the same object');
assert(!box.repeatedAnsweredQuestion('Do you know what it actually is?'),'an unbound pronoun is not enough for suppression');
assert.match(box.answeredQuestionContext('yellow jug'),/not instructions or visual verification/);
clock+=1000;box.rememberSpokenQuestion(ask);box.captureSocialAnswer('Drew say happy birthday');
assert.equal(box.MEM.answeredQuestions.length,1,'unrelated command is not saved as an answer');
assert.equal(box.lastOpenSocialQuestion(),null);
clock+=1000;box.rememberSpokenQuestion(ask);box.captureSocialAnswer('Yes');
assert.equal(box.MEM.answeredQuestions.length,1,'a bare yes does not supply object identity');
// A yes/no reply does not justify treating an identity as resolved.
clock+=1000;box.rememberSpokenQuestion('What is the blue bottle?');box.captureSocialAnswer('Yes');
assert.equal(box.MEM.answeredQuestions.length,1);
clock+=1000;box.rememberSpokenQuestion('What is the blue bottle?');box.MEM.currentPerson='other';box.captureSocialAnswer('A water bottle');
assert.equal(box.MEM.answeredQuestions.length,1,'different person is not silently substituted for the intended respondent');
box.MEM.currentPerson='aaron';
const snapshot=JSON.parse(JSON.stringify(box.MEM));box.MEM=snapshot;
assert.match(box.answeredQuestionContext('yellow jug'),/adhesive remover/,'answer survives serialization and unrelated turns');
box.MEM={initiatives:[{t:clock,text:ask,question:'Do you know what it actually is?',answer:'Drew say happy birthday',answeredAt:clock}],answeredQuestions:[],currentPerson:'aaron',
 conversations:[{t:clock,person:'aaron',user:"It's not cleaning it's adhesive remover",owl:"Wait, adhesive remover — is that what's in that yellow jug I was supposed to check on?"}]};
box.restoreQuestionContinuity();box.restoreQuestionContinuity();
assert.equal(box.MEM.answeredQuestions.length,1,'backfill is idempotent and rejects the observed unrelated historical answer');
assert.match(box.MEM.answeredQuestions[0].source,/inferred/);
assert.equal(box.MEM.conversations.length,1,'original evidence remains untouched');
assert.match(html,/rememberSpokenQuestion\(text\)/,'all accepted voice paths, including speak, track questions');
assert.match(html,/answeredQuestionContext\(userTurn\)/);
assert.match(fs.readFileSync(root+'executive-context.js','utf8'),/answeredQuestionContext\(query\)/);
assert(saves>0);console.log('PASS: durable attributed answers, paraphrase suppression, distinct follow-ups, topic/person changes, original correction recovery and prompt/voice integration.');
