const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const html=fs.readFileSync(path.join(__dirname,'../app/src/main/assets/growbot-brain.html'),'utf8');
const elements={channelEnabled:{type:'select-one',value:'unused'},channelA:{type:'number',value:'1234'},channelName:{type:'text',value:'Custom joint'}};
const original={channel:0,enabled:true,name:'Old name',a_us:1400,b_us:1700};
const box={$:selector=>elements[selector.slice(1)],channelDraft:()=>original,CHANNEL_FIELDS:{channelEnabled:'enabled',channelA:'a_us',channelName:'name'}};
vm.createContext(box);
vm.runInContext(html.slice(html.indexOf('function channelMidpoint('),html.indexOf('function readChannelDraft(){')),box);
vm.runInContext(html.slice(html.indexOf('function readChannelDraft(){'),html.indexOf('function channelLabels(){')),box);
vm.runInContext(html.slice(html.indexOf('function channelOptionLabel('),html.indexOf('function channelDraft(){')),box);
assert.equal(box.readChannelDraft().enabled,false);
assert.equal(box.readChannelDraft().a_us,1234);
assert.equal(box.readChannelDraft().name,'Custom joint');
assert.equal(box.readChannelDraft().channel,0,'renaming preserves the physical socket');
assert.equal(box.readChannelDraft().b_us,1700,'renaming preserves unedited limits');
assert.equal(box.readChannelDraft().center_us,1467,'typed endpoints determine the center');
assert.equal(box.channelMidpoint(1561,1112),1337,'reversed endpoints and odd sums round consistently');
assert.equal(box.channelMidpoint(1112,1561),1337,'endpoint order does not matter');
assert.equal(box.channelMidpoint(500,2500),1500);
assert.equal(box.channelMidpoint('',1500),null,'incomplete edits are not treated as zero');
assert.equal(box.channelMidpoint(499,1500),null,'invalid endpoints are not silently clamped');
assert.equal(box.channelMidpoint(1500.5,1700),null);
assert.match(html,/id="channelCenter"[^>]*readonly/,'center cannot be manually overwritten');
assert.ok(html.indexOf('id="channelName"')<html.indexOf('id="channelIdentity"'),'label must be visible outside collapsed group options');
assert.equal(original.enabled,true,'editing must not mutate saved config');
elements.channelEnabled.value='installed';assert.equal(box.readChannelDraft().enabled,true);
for(let channel=0;channel<16;channel++)assert.equal(box.channelOptionLabel({...original,channel,enabled:false}),`Ch ${channel} · Unconnected`);
assert.equal(box.channelOptionLabel({...original,enabled:true}),'Ch 0 · Old name');
console.log('PASS: Unused on all 16 channels, installed round-trip, typed draft values and saved state preserved.');
(async()=>{
 const sent=[];const options=[{value:'1',textContent:''}];
 const saved={channel:1,enabled:true,name:'Leg',a_name:'Up',b_name:'Down',a_us:1561,b_us:1112,center_us:1200,locked:false};
 const saveBox={CHANNEL_SETUP:{loaded:true,generation:0,saved:[{},saved],drafts:{}},channelMidpoint:box.channelMidpoint,
   channelCommand:async(action,{config})=>{assert.equal(action,'save');sent.push({...config});return {saved_channel:{...config}};},
   localStorage:{setItem:()=>{}},$:()=>({options}),channelOptionLabel:()=>'',renderChannelEditor:()=>{},channelMessage:()=>{}};
 vm.createContext(saveBox);
 vm.runInContext(html.slice(html.indexOf('async function saveChannelConfiguration('),html.indexOf('async function moveChannelLive(')),saveBox);
 await saveBox.saveChannelConfiguration({...saved});
 assert.equal(sent[0].center_us,1337,'saved payload uses midpoint even if given an old center');
 assert.equal(sent[0].a_us,1561);assert.equal(sent[0].b_us,1112);
 saveBox.CHANNEL_SETUP.saved[1]={...saved,locked:true};
 await saveBox.saveChannelConfiguration({...saved,locked:false});
 assert.equal(sent[1].center_us,1200,'unlocking stays lock-only so firmware accepts it');
 await saveBox.saveChannelConfiguration({...saved});
 assert.equal(sent[2].center_us,1337,'subsequent endpoint save computes the center');
 saveBox.CHANNEL_SETUP.saved[1]={...saved};
 await saveBox.saveChannelConfiguration({...saved,name:"",group:"",enabled:false},{identityOnly:true});
 assert.equal(sent[3].name,"Channel 1");assert.equal(sent[3].enabled,false);
 assert.equal(sent[3].center_us,1200);assert.equal(sent[3].a_us,1561);assert.equal(sent[3].b_us,1112);
 saveBox.CHANNEL_SETUP.saved[0]={channel:0,enabled:true,name:"Taken"};
 await assert.rejects(()=>saveBox.saveChannelConfiguration({...saved,name:"Taken"}),/already assigned to Ch 0/);
 assert.equal(sent.length,4,"duplicate label never sends a write");
 console.log('PASS: midpoint persisted with endpoint save; locked-channel unlock remains compatible.');
})().catch(e=>{console.error(e);process.exitCode=1});
