const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=__dirname+'/../app/src/main/assets/';
const html=fs.readFileSync(root+'growbot-brain.html','utf8');
let clock=1800000000000,saves=0;
const b={Date:class extends Date{static now(){return clock}},MEM:{currentPerson:'aaron'},memSave:()=>saves++};
vm.createContext(b);vm.runInContext(fs.readFileSync(root+'question-continuity.js','utf8'),b);
const invitation="While you fix that, here's a tiny game: I pick a color, you guess it, and I'll only say hotter or colder. My first clue is that it's a color I've been hunting all day.";
b.rememberDeliveredSpeech(invitation);
clock+=18000;b.rememberAcceptedUserSpeech('is it gray');
assert.equal(b.MEM.sharedActivity.state,'open');
assert.equal(b.MEM.sharedActivity.text,invitation);
assert.equal(b.MEM.sharedActivity.replies[0].text,'is it gray');
assert.match(b.spokenContinuityContext(),/I pick a color/);
assert.match(b.spokenContinuityContext(),/is it gray/);
assert.match(b.spokenContinuityContext(),/Do not claim a missing recall result/);
// A transcript shaped as a question remains attached to the invitation.
b.rememberAcceptedUserSpeech('Is it blue?');
assert.equal(b.MEM.sharedActivity.replies.at(-1).text,'Is it blue?');
// Ordinary recent-history eviction and process restart must not lose the game.
for(let i=0;i<15;i++)b.rememberDeliveredSpeech('Brief aside '+i);
assert.equal(b.MEM.deliveredExchange.length,12);
b.MEM=JSON.parse(JSON.stringify(b.MEM));
assert.match(b.spokenContinuityContext(),/I pick a color/);
assert.match(b.spokenContinuityContext(),/clear new topic or stop takes priority/);
b.MEM.currentPerson='other';assert.equal(b.spokenContinuityContext(),'');
b.rememberAcceptedUserSpeech('Stop');assert.equal(b.MEM.sharedActivity.state,'open','different person does not close attributed activity');
b.MEM.currentPerson='aaron';b.rememberAcceptedUserSpeech('Stop the game. Tell me why the moon changes shape.');
assert.equal(b.MEM.sharedActivity.state,'closed');
assert(!b.spokenContinuityContext().includes('UNFINISHED PLAY INVITATION'));
b.rememberDeliveredSpeech("Let's play a riddle game. Guess my animal.");
assert.equal(b.MEM.sharedActivity.state,'open');
b.rememberAcceptedUserSpeech("Let's talk about something else");assert.equal(b.MEM.sharedActivity.state,'closed');
b.rememberDeliveredSpeech(invitation);clock+=25*60*60*1000;
assert(!b.spokenContinuityContext().includes('UNFINISHED PLAY INVITATION'),'old game is evidence, not a permanent active command');
b.rememberDeliveredSpeech("Here's a new game: guess my color.",{action:'start',kind:'color',answer:'blue'});
assert.equal(b.MEM.sharedActivity.privateAnswer,'blue');
b.rememberAcceptedUserSpeech('Is it red?');
b.rememberDeliveredSpeech('Colder! You guess again.',{action:'start',kind:'color',answer:'red'});
assert.equal(b.MEM.sharedActivity.privateAnswer,'blue','continuation cannot silently replace the answer');
b.rememberDeliveredSpeech('Yes, blue! You got it.',{action:'finish'});
assert.equal(b.MEM.sharedActivity.state,'closed');
assert.match(b.spokenContinuityContext(),/do not fabricate hotter\/colder/);
// The full system-prompt entry point covers social, local, and executive routes.
b.buildExecutiveContext=()=> 'BASE';
b.spokenAnswerContract=()=> '';
vm.runInContext(html.slice(html.indexOf('function systemPrompt('),html.indexOf('/** Is there enough configuration',html.indexOf('function systemPrompt('))),b);
assert.match(b.systemPrompt('hello'),/SHARED SPOKEN EXCHANGE/);
assert.match(html,/if\(APP.resting\|\|APP.settings\) return false;[\s\S]*?if\(typeof rememberAcceptedUserSpeech/);
assert(saves>0);
console.log('PASS spoken continuity: exact color-game reproduction, questions as guesses, bounded persistence, person isolation, stop/topic priority, expiry and all prompt routes.');
