const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const data=new Map(),status={textContent:''};
const box={localStorage:{getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v)},NW:{plan:{version:1,speed_us_s:1600,lift_percent:50,steps:[{channel:1,position:'Up',binding:{a_us:500}}]}},CHANNEL_SETUP:{loaded:true},$:()=>status};
vm.createContext(box);const source=fs.readFileSync(path.join(__dirname,'../app/src/main/assets/travel-estimate.js'),'utf8');vm.runInContext(source,box);
const sample={cycles:6,feet:1,pace:'run',direction:'forward',surface:'carpet'},request={distance_ft:3,pace:'run',direction:'forward',surface:'carpet'};
assert.equal(box.estimateTravel(request).calibrated,false,'no measurement means unknown, not a guessed camera distance');
box.saveTravelMeasurement(sample);let r=box.estimateTravel(request);
assert.equal(r.nominalCycles,18);assert.equal(r.nextSegmentCycles,18);assert.equal(r.actualPositionKnown,false);assert.equal(r.observedCycleRange,null);
assert.equal(box.estimateTravel({...request,distance_ft:10}).nextSegmentCycles,30);
assert.equal(box.estimateTravel({...request,distance_ft:0}).nominalCycles,0);
assert.equal(box.estimateTravel({...request,stop_short_ft:1}).nominalCycles,12);
assert.equal(box.estimateTravel({...request,distance_ft:5,target_fraction:.5}).travelFt,2.5);
assert.equal(box.estimateTravel({...request,distance_ft:5,target_fraction:1/3}).nominalCycles,10);
assert.equal(box.estimateTravel({...request,distance_ft:5,target_fraction:.5,stop_short_ft:1}).travelFt,2.5,'stand-off caps approach; it does not shrink the halfway destination');
assert.equal(box.estimateTravel({...request,distance_ft:.1}).wholeCyclesBeforeTarget,0,'never round a short approach into an obstacle');
box.spatialSnapshot=()=>({visualTarget:{status:'likely',target:'white wall',bodySector:'forward',distanceMm:1524,ageMs:100}});
assert.equal(box.estimateTravel({...request,use_visual_range:true,target:'wall',target_fraction:.5}).nominalCycles,15);
assert.equal(box.estimateTravel({...request,use_visual_range:true,target:'person'}).calibrated,false);
assert.equal(box.estimateTravel({...request,use_visual_range:true,direction:'backward'}).calibrated,false);
box.spatialSnapshot=()=>({visualTarget:{status:'likely',target:'wall',bodySector:'right',distanceMm:1524,ageMs:100}});
assert.equal(box.estimateTravel({...request,use_visual_range:true}).calibrated,false,'sideways camera range is not forward body travel');
box.spatialSnapshot=()=>({visualTarget:null});assert.equal(box.estimateTravel({...request,use_visual_range:true}).calibrated,false);
assert.throws(()=>box.estimateTravel({...request,target_fraction:2}));
for(const delta of [{pace:'slow'},{direction:'backward'},{surface:'tile'}])assert.equal(box.estimateTravel({...request,...delta}).calibrated,false);
box.NW.plan.cycles=3;assert.equal(box.estimateTravel(request).calibrated,true,'number requested does not change the per-cycle gait');
box.NW.plan.lift_percent=60;assert.equal(box.estimateTravel(request).calibrated,false,'changed lift invalidates old calibration');box.NW.plan.lift_percent=50;
box.saveTravelMeasurement({...sample,cycles:6,feet:1.2});r=box.estimateTravel(request);assert.deepEqual(Array.from(r.observedCycleRange),[15,18]);
box.saveTravelMeasurement({...sample,surface:'tile'});assert.equal(box.estimateTravel({...request,surface:''}).calibrated,false,'different floors cannot silently mix');
box.saveTravelMeasurement({...sample,feet:0});assert.equal(box.estimateTravel(request).calibrated,false,'feet cycling without travel is not a distance estimate');
box.undoTravelMeasurement();assert.equal(box.estimateTravel(request).calibrated,true);
for(const bad of [{distance_ft:NaN},{distance_ft:-1},{distance_ft:Infinity},{pace:'turbo'}])assert.throws(()=>box.estimateTravel({...request,...bad}));
box.NW.running=true;assert.throws(()=>box.saveTravelMeasurement(sample));box.NW.running=false;
data.set('owlbot_travel_calibration_v1','corrupt');assert.throws(()=>box.saveTravelMeasurement(sample));assert.equal(data.get('owlbot_travel_calibration_v1'),'corrupt','bad stored data must not be erased');
assert.doesNotMatch(source,/channelCommand\(|wsSend\(|runNamedForwardWalk\(/);
console.log('PASS: measured distance/cycle estimates, gait-speed-surface isolation, uncertainty, zero-travel rejection, undo and no motor commands.');
