const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const html=fs.readFileSync(path.join(__dirname,'../app/src/main/assets/growbot-brain.html'),'utf8');
const elements={mProvider:{value:'ollama-cloud'},mBase:{value:'https://ollama.com/v1'},mModel:{value:'test-brain'},mVisionModel:{value:'test-vision'},mKey:{value:'FAKE_TEST_ONLY'},mVisionRoute:{value:'local'},localVisionTools:{open:true},mModels:{textContent:''}};
const p={'ollama-cloud':{base:'https://ollama.com/v1',needsKey:true},'tower-local':{tower:true,localOnly:true,needsKey:false},custom:{needsKey:true}};
let saves=0,clears=0;
const box={URL,DOMException,PROVIDERS:p,$:s=>elements[s.slice(1)],MIND:{vision:true},PERCEPTION:{},MODEL_TEST:null,MODEL_DISCOVERY:null,localVisionRoute:()=>elements.mVisionRoute.value,localVisionReady:()=>false,towerBaseLoad:()=>'http://192.168.50.2:11434/v1',populateModels:()=>clears++,prefsSave:()=>saves++,readLocalVisionStatus:()=>{},refreshProviderUI:()=>{}};
vm.createContext(box);
vm.runInContext(html.slice(html.indexOf('function isCloudBackedModel('),html.indexOf('/* One shared request budget')),box);
vm.runInContext(html.slice(html.indexOf('function mindConfigured(){'),html.indexOf('function startMind(){')),box);
vm.runInContext(html.slice(html.indexOf('function selectModelProvider('),html.indexOf('async function testModelConnection(')),box);
assert.equal(box.mindConfigured(),null,'missing phone eye must not block cloud text brain');
elements.mBase.value='http://192.168.50.2:11434/v1';assert.throws(()=>box.mindHeaders(),/Ollama Cloud needs/,'never send a cloud key to a stale tower URL');
box.selectModelProvider('ollama-cloud');assert.equal(elements.mBase.value,'https://ollama.com/v1');assert.equal(elements.mVisionRoute.value,'cloud');assert.equal(elements.localVisionTools.open,false);assert.equal(elements.mKey.value,'FAKE_TEST_ONLY');assert.equal(saves,1);assert.equal(clears,1);
assert.equal(box.mindHeaders().Authorization,'Bearer FAKE_TEST_ONLY');
elements.mKey.value='';assert.equal(box.mindConfigured(),'no API key');
elements.mProvider.value='tower-local';box.selectModelProvider('tower-local');assert.equal(box.mindConfigured(),null);assert(!('Authorization' in box.mindHeaders()));
elements.mVisionRoute.value='local';assert.equal(box.mindConfigured(),null);assert.equal(elements.mVisionRoute.value,'local','explicit phone-only choice is never silently cloud-fallback');
for(const code of [401,403,404,429])assert(box.modelConnectionError({status:code}).includes(String(code)));
assert(box.modelConnectionError(Error('Failed to fetch')).includes('does not prove the key is invalid'));
assert(!html.slice(html.indexOf('async function testModelConnection('),html.indexOf('function refreshProviderUI(')).includes('grabFrameDataUrl'),'diagnostic never captures a real photo');
console.log('PASS: provider switch selects hosted vision, stale tower URL rejects cloud key, text brain independent of local eye, local privacy and useful errors.');
