const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.join(__dirname,'../app/src/main/assets');
const source=fs.readFileSync(path.join(root,'inquiry-progress.js'),'utf8');
let clock=100000,saved={},failSave=false;
const original={id:'mouse-1',status:'resolved',target:'small black device on the desk near the keyboard',question:'What is the small black device sitting on the desk near the keyboard?',updated:90000,evidence:[{text:'The small black device is a computer mouse.'}]};
const b={Date:{now:()=>clock},Math,Number,JSON,Set,WONDER:{threads:[original]},MIND:{},TASKS:{items:[]},
 localStorage:{getItem:k=>saved[k]||null,setItem:(k,v)=>{if(failSave)throw Error('full');saved[k]=v;}}};
vm.createContext(b);vm.runInContext(source,b);
const duplicate={question:'What is the small black device on the desk, and what does it do?',target:'small black device on the desk'};
assert.match(b.completedInquiryGate(duplicate),/Already investigated/,'Real repeated mouse question is closed');
assert.equal(b.quietCompletedInquiryQuestions(duplicate.question+' There is a blue box ahead.'),'There is a blue box ahead.');
assert.equal(b.quietCompletedInquiryQuestions('I remember that device is a mouse.'),'I remember that device is a mouse.','A relevant callback is not an unanswered question');
assert(b.completedInquiryRecords()[0].text.includes('computer mouse'));
b.WONDER.threads=[];vm.runInContext('COMPLETED_INQUIRIES.records=[];loadCompletedInquiries()',b);
assert.match(b.completedInquiryGate(duplicate),/Already investigated/,'Completion survives working-journal rotation and reload');
assert.equal(b.completedInquiryGate({...duplicate,question:'What color is the small black device on the desk?'}),'','A genuinely different aspect can be investigated');
assert.equal(b.completedInquiryGate({...duplicate,question:'What is inside the small black device on the desk?'}),'','Identification does not answer hidden contents');
assert.equal(b.completedInquiryGate({...duplicate,question:'What is the small black device on the desk used for?'}),'','Purpose is a different question');
assert.equal(b.completedInquiryGate({...duplicate,target:'small blue device on the desk',question:'What is the small blue device on the desk?'}),'','Different-colored objects are not silently merged');
assert.equal(b.completedInquiryGate({...duplicate,target:'large refrigerator',question:'What is the large refrigerator?'}),'');
assert.match(b.completedInquiryGate({...duplicate,revisitReason:'I want to look again',newEvidenceId:'fake'}),/Already investigated/);
vm.runInContext("INQUIRY.evidence=[{id:'new',at:95000,novel:true,text:'The small black device on the desk near the keyboard is now open, with loose parts beside it.'}]",b);
assert.equal(b.completedInquiryGate({...duplicate,revisitReason:'Its housing has opened since the earlier observation.',newEvidenceId:'new'}),'');
clock=170000;assert.match(b.completedInquiryGate({...duplicate,revisitReason:'The housing is open now',newEvidenceId:'new'}),/Already investigated/,'Stale evidence cannot reopen');
b.MIND.activeUserTurn=true;b.MIND.activeRequest={text:'Please check that device again.'};assert.equal(b.completedInquiryGate(duplicate),'','Explicit owner recheck is allowed');
b.MIND.activeUserTurn=false;assert.match(b.completedInquiryGate(duplicate),/Already investigated/,'An old user request cannot reopen during autonomy');
b.rememberCompletedInquiry({...original,id:'open',status:'open'});assert.equal(b.completedInquiryRecords().length,1,'Open/abandoned questions are not completed facts');
failSave=true;b.rememberCompletedInquiry({...original,id:'mouse-2'});assert.match(vm.runInContext('COMPLETED_INQUIRIES.saveError',b),/not confirmed/);
const html=fs.readFileSync(path.join(root,'growbot-brain.html'),'utf8'),memory=fs.readFileSync(path.join(root,'context-memory.js'),'utf8');
assert.match(html,/if\(completed\)return completed/);assert.match(html,/rememberCompletedInquiry\(thread\)/);assert.match(memory,/records\.push\(\.\.\.completedInquiryRecords\(\)\)/);
console.log('PASS completed investigations: real repeated mouse case, persistent migration/reload, distinct target/question, changed-evidence or explicit recheck only, retrieval and storage failure reporting.');
