const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../app/src/main/assets/named-walk.js'),'utf8');
const fields=Object.fromEntries(Object.entries({walkSpeed:'800',walkCycles:'3',walkLift:'50',walk_lf:'1',walk_rr:'3',walk_rf:'5',walk_lr:'2',walk_slide:'6',namedWalkStatus:''}).map(([k,value])=>[k,{value,textContent:''}]));
const rows=[1,2,3,5,6].map(channel=>({channel,name:'Joint '+channel,enabled:true,calibrated:true,a_name:channel===6?'Back':'Up',b_name:channel===6?'Forward':'Down',a_us:1200,b_us:1800,center_us:1500}));
fields.walkPaired={checked:true};fields.walkSettle={value:'20'};
const box={CHANNEL_SETUP:{saved:rows},$:s=>fields[s.slice(1)]};
vm.createContext(box);vm.runInContext(source.slice(0,source.indexOf('async function saveNamedForwardWalk')),box);
vm.runInContext('showNamedWalkPlan=()=>{};NW.plan=namedWalkEditorPlan();NW.dirty=true',box);
assert.equal(box.refreshNamedWalkDirty(),false,'spurious change event must clear when values match');
fields.walkSpeed.value='600';assert.equal(box.refreshNamedWalkDirty(),true);
box.receiveNamedWalkPlan(vm.runInContext('NW.plan',box));
assert.equal(fields.walkSpeed.value,'600','telemetry must not erase actual edits');
assert.equal(vm.runInContext('NW.dirty',box),true);
fields.walkSpeed.value='800';assert.equal(box.refreshNamedWalkDirty(),false,'reverting an edit clears dirty');
fields.walkCycles.value='';assert.equal(box.refreshNamedWalkDirty(),true,'incomplete numeric input is not saved');
fields.walkCycles.value='3';assert.equal(box.refreshNamedWalkDirty(),false);
fields.walk_rf.value='1';assert.equal(box.refreshNamedWalkDirty(),true,'duplicate mapping is an actual invalid edit');
fields.walk_rf.value='5';assert.equal(box.refreshNamedWalkDirty(),false);
rows[0].a_us+=1;assert.equal(box.refreshNamedWalkDirty(),true,'changed calibration cannot silently reuse old walk binding');
rows[0].a_us-=1;assert.equal(box.refreshNamedWalkDirty(),false);
fields.walkSpeed.value='600';box.refreshNamedWalkDirty();
const freshlySaved=box.namedWalkEditorPlan();box.receiveNamedWalkPlan(freshlySaved);
assert.equal(vm.runInContext('NW.dirty',box),false,'a matching fresh Pico plan clears stale dirty state');
console.log('PASS: no-op edits, revert, invalid inputs, real edits, calibration changes, and fresh Pico confirmation.');
