const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{createHash}=require('node:crypto');
const core=require('../app/src/main/assets/story-core.js');
const context={};vm.createContext(context);vm.runInContext(fs.readFileSync(__dirname+'/../app/src/main/assets/story-library.js','utf8')+';globalThis.library=STORY_LIBRARY;',context);
const library=context.library;
assert.equal(library.length,24);
const originals=library.filter(s=>s.kind==='historical');assert.equal(originals.length,12);
const counts=[134,133,101,56,122,128,283,1271,1427,409,950,3873];
library.forEach(story=>{
 if(story.kind==='historical')assert.equal(story.words,counts[originals.indexOf(story)]);
 assert.equal(createHash('sha256').update(story.text).digest('hex'),story.sha256);
 const parts=core.plan(story.text);assert(parts.length>0);assert(parts.every(p=>p.text.length<=420));
 assert.equal(parts.map(p=>p.text).join('').replace(/\s/g,''),story.text.replace(/\s/g,''),story.id+' preserves EVERY word and punctuation mark');
 assert(!story.text.includes('[Illustration'));assert(!story.text.includes('PROJECT GUTENBERG'));
});
assert(library.find(s=>s.id==='hare-tortoise').text.endsWith('Slow but steady wins the race.'));
assert(library.find(s=>s.id==='peter-rabbit').text.endsWith('for supper.\n\nTHE END'));
assert(library.find(s=>s.id==='velveteen-rabbit').text.endsWith('to be Real.'));
assert(core.plan(library.find(s=>s.id==='goldilocks').text).some(p=>p.role==='big bear'&&p.pitch<0));
assert(core.plan(library.find(s=>s.id==='goldilocks').text).some(p=>p.role==='little bear'&&p.pitch>0));
const base={name:'en-US-AnaNeural',engine:'microsoft',pitch:0,rate:22,style:''},clone={...base};
assert(core.voice(base,'excited').pitch>base.pitch);assert(core.voice(base,'sad').pitch<base.pitch);
assert.equal(core.voice(base,'afraid',{comfort:true}).pitch,-1);assert(core.voice(base,'neutral',{bedtime:true}).rate<base.rate);
assert.deepEqual(base,clone,'Mood must not mutate owner voice settings');
for(const emotion of ['sad','excited','playful'])assert.equal(core.voice(base,emotion).name,base.name);
assert.equal(core.comfortNeed("I'm scared of that story"),'comfort');
assert.equal(core.comfortNeed("I'm hurt"),'urgent');assert.equal(core.comfortNeed("I can't breathe"),'urgent');
assert.equal(core.comfortNeed('Tell a story about a child saying I am scared'),'');
assert.equal(core.comfortNeed("I'm not scared"),'');assert.equal(core.comfortNeed('I had a nightmare'),'comfort');
assert.equal(core.findStory(library,'read goldilocks').id,'goldilocks-child');assert.equal(core.findStory(library,'read Cinderella'),undefined);
assert.equal(core.findStory(library,'read the historical goldilocks').id,'goldilocks');
assert.equal(core.editionStory(library,'hare-tortoise').id,'hare-tortoise-child');
assert.equal(core.editionStory(library,'hare-tortoise-child',true).id,'hare-tortoise');
console.log('Story core: 12 originals + 12 retellings, full texts, endings, edition routing, character delivery, unchanged identity, mood and distress checks passed');
